apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-config
  labels:
    app: catalogue
    env: production
    version: v1.0
    tier: backend
  annotations:
    maintainer: "Double Abdelrahman"  
    description: "Catalogue Service ConfigMap for Robot Shop Microservices"
data:
  MYSQL_HOST: mysql
  MYSQL_USER: shipping
  MYSQL_DATABASE: cities
