apiVersion: v1
kind: Secrets
metadata:
  name: shipping-secrets
  labels:
    app: shipping
    env: production
    version: v1.0
    tier: backend
  annotations:
    maintainer: "Double Abdelrahman"
    description: "Shipping Service Secrets for Robot Shop Microservices"
data:
  MYSQL_PASSWORD: "c2VjcmV0"
