services:
  mongodb:
    build:
      context: mongo
    image: ${REPO}/rs-mongodb:${TAG}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      CATALOGUE_MONGO_USER: ${CATALOGUE_MONGO_USER}
      CATALOGUE_MONGO_PASSWORD: ${CATALOGUE_MONGO_PASSWORD}
      CATALOGUE_MONGO_DATABASE: ${CATALOGUE_MONGO_DATABASE}
      USER_MONGO_USER: ${USER_MONGO_USER}
      USER_MONGO_PASSWORD: ${USER_MONGO_PASSWORD}
      USER_MONGO_DATABASE: ${USER_MONGO_DATABASE}
    volumes:
      - mongo-data:/var/lib/mongodb:ro
    networks:
      - data-services

  redis:
    image: redis:latest
    networks:
      - data-services

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    networks:
      - message-queue

  catalogue:
    build:
      context: catalogue
    image: ${REPO}/rs-catalogue:${TAG}
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://${CATALOGUE_MONGO_USER}:${CATALOGUE_MONGO_PASSWORD}@mongodb:27017/${CATALOGUE_MONGO_DATABASE}
    networks:
      - api-services
      - data-services
    healthcheck:
      test: [ "CMD", "curl", "-H", "X-INSTANA-SYNTHETIC: 1", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 3

  user: #------#
    build:
      context: user
    image: ${REPO}/rs-user:${TAG}
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URL: mongodb://${USER_MONGO_USER}:${USER_MONGO_PASSWORD}@mongodb:27017/${USER_MONGO_DATABASE}
    networks:
      - api-services
      - data-services
    healthcheck:
      test: [ "CMD", "curl", "-H", "X-INSTANA-SYNTHETIC: 1", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 3

  cart:
    build:
      context: cart
    image: ${REPO}/rs-cart:${TAG}
    depends_on:
      - redis
    networks:
      - api-services
      - data-services
    healthcheck:
      test: [ "CMD", "curl", "-H", "X-INSTANA-SYNTHETIC: 1", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 3

  mysql:
    build:
      context: mysql
    image: ${REPO}/rs-mysql-db:${TAG}
    environment:
      SHIPPING_MYSQL_USER: ${SHIPPING_MYSQL_USER}
      SHIPPING_MYSQL_PASSWORD: ${SHIPPING_MYSQL_PASSWORD}
      SHIPPING_MYSQL_DATABASE: ${SHIPPING_MYSQL_DATABASE}
      RATINGS_MYSQL_USER: ${RATINGS_MYSQL_USER}
      RATINGS_MYSQL_PASSWORD: ${RATINGS_MYSQL_PASSWORD}
      RATINGS_MYSQL_DATABASE: ${RATINGS_MYSQL_DATABASE}
    cap_add:
      - NET_ADMIN
    volumes:
      - mysql-data:/var/lib/mysql/:ro
    networks:
      - data-services

  shipping:
    build:
      context: shipping
    image: ${REPO}/rs-shipping:${TAG}
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${SHIPPING_MYSQL_USER}:${SHIPPING_MYSQL_PASSWORD}@mysql:3306/${SHIPPING_MYSQL_DATABASE}?useSSL=false&autoReconnect=true
    networks:
      - api-services
      - data-services
    healthcheck:
      test: ["CMD", "curl", "-H", "X-INSTANA-SYNTHETIC: 1", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 3

  ratings:
    build:
      context: ratings
    image: ${REPO}/rs-ratings:${TAG}
    environment:
      PDO_URL: mysql:host=mysql;port=3306;dbname=${RATINGS_MYSQL_DATABASE};user=${RATINGS_MYSQL_USER};password=${RATINGS_MYSQL_PASSWORD};charset=utf8mb4
    networks:
      - api-services
      - data-services
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-H", "X-INSTANA-SYNTHETIC: 1", "-f", "http://localhost/_health"]
      interval: 10s
      timeout: 10s
      retries: 3

  payment:
    build:
      context: payment
    image: ${REPO}/rs-payment:${TAG}
    depends_on:
      - rabbitmq
    networks:
      - api-services
      - message-queue
    healthcheck:
      test: ["CMD", "curl", "-H", "X-INSTANA-SYNTHETIC: 1", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 3

  dispatch: #------#
    build:
      context: dispatch
    image: ${REPO}/rs-dispatch:${TAG}
    depends_on:
      - rabbitmq
    networks:
      - message-queue

  web: #------#
    build:
      context: web
      args:
        # agent key to download tracing libs
        KEY: ${INSTANA_AGENT_KEY}
    image: ${REPO}/rs-web:${TAG}
    depends_on:
      - catalogue
      - user
      - shipping
      - payment
    ports:
      - "8080:8080"
    networks:
      - frontend
      - api-services
    healthcheck:
      test: [ "CMD", "curl", "-H", "X-INSTANA-SYNTHETIC: 1", "-f", "http://localhost:8080/" ]
      interval: 10s
      timeout: 10s
      retries: 3
    # Uncomment to enable Instana EUM
    # environment:
      # INSTANA_EUM_KEY: <your eum key>
      # INSTANA_EUM_REPORTING_URL: <your reporting url>

volumes:
  mysql-data:
  mongo-data:

networks:
  frontend:
  api-services:
  data-services:
  message-queue:
