apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch-deployment
  labels:
    app: dispatch
spec:
  
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
      - name: dispatch
        image: robotshop/rs-dispatch:2.1.0
