apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: defectdojo-admin-secrets
  namespace: dojo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: defectdojo-admin-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /prod/dojo/credentials
