apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-secrets-mapping
  namespace: robotshop
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: mongo-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /prod/mongo/credentials
