apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencost-cloud-integration
  namespace: opencost
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: cloud-integration
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /prod/opencost/cloud-integration
