apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
    env: production
    version: v2.1.0
    tier: backend
  annotations:
    deployment.kubernetes.io/name: "cart"
    deployment.kubernetes.io/version: "2.1.0"
    maintainer: "Double Abdelrahman"
    description: "Deployment for Robot Shop Cart Service"
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
        tier: backend
    spec:
      containers:
      - name: cart
        image: robotshop/rs-cart:2.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        startupProbe: 
          httpGet:
            path: /actuator/health
            port: 8080
          failureThreshold: 60   # 30 attempts to check if the app is started
          periodSeconds: 10       # check every 10 seconds

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60 # give some time to start the app
          periodSeconds: 10 # check every 10 seconds
          timeoutSeconds: 5
          failureThreshold: 3 # after 3 failures, consider the pod unhealthy

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20 # give some time to start the app
          periodSeconds: 5 # check every 5 seconds
          timeoutSeconds: 3 # wait for 3 seconds
          failureThreshold: 3 # after 3 failures, consider the pod not ready
