apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  labels:
    app: mysql
    env: production
    version: v1.0
    tier: database
  annotations:
    maintainer: "Double Abdelrahman"
    description: "MySQL Secrets for Robot Shop Microservices"
data:
  # MySQL Root Credentials
  MYSQL_ROOT_PASSWORD: "Y2hhbmdlX21lX3Jvb3RfcGFzc3dvcmQ="

  # Shipping MySQL Credentials
  SHIPPING_MYSQL_USER: "c2hpcHBpbmc="
  SHIPPING_MYSQL_PASSWORD: "c2VjcmV0"
  SHIPPING_MYSQL_DATABASE: "Y2l0aWVz"

  # Ratings MySQL Credentials
  RATINGS_MYSQL_USER: "cmF0aW5ncw=="
  RATINGS_MYSQL_PASSWORD: "aWxvdmVpdA=="
  RATINGS_MYSQL_DATABASE: "cmF0aW5ncw=="
