# Certificate for Robot Shop web application
# Deployed in robotshop namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: robotshop-tls
  namespace: robotshop
spec:
  secretName: robotshop-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - shebl22.me
    - www.shebl22.me
