apiVersion: v1
kind: secrets
metadata:
  name: catalogue-secrets
  labels:
    app: catalogue
    env: production
    version: v1.0
    tier: backend
  annotations:
    maintainer: "Double Abdelrahman"
    description: "Catalogue Service Secrets for Robot Shop Microservices"
data:
  MONGO_PASSWORD: "Y2F0YWxvZ3VlMTIz"
