apiVersion: v1
kind: Service 
metadata:
  name: catalogue
  labels:
    app: catalogue
    env: production
    version: v2.1.0
    tier: backend
  annotations:  
    maintainer: "Double Abdelrahman"
    description: "Service for Robot Shop Catalogue Service"
spec:
  type: ClusterIP
  selector:
    app: catalogue
  ports:
  - name: http
    port: 8080
    targetPort: 8080

