# 1. Global Settings
# This is the domain you will use to access the dashboard

# Keep this true so the chart creates the 'defectdojo' secret needed by all containers
createSecret: false

# -- create valkey secret in defectdojo chart, outside of valkey chart
createValkeySecret: false

# -- create postgresql secret in defectdojo chart, outside of postgresql chart
createPostgresqlSecret: false

admin:
  user: admin
  password: ""

host: "" 
siteUrl: ""

# 2. Django (uWSGI): The web interface and API.
django:
  replicas: 1
# ADD THIS BLOCK: Give Django enough RAM to survive password hashing
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi # Raised to prevent OOMKilled during login
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/backend-protocol: "http"
    # TLS certificate from cert-manager
    tls:
      - secretName: defectdojo-tls
        hosts:
          - ""

    hosts:
      - ""

# Celery Worker: The background processor (this does the heavy lifting, like importing scans and deduplicating findings).
# 3. Background Workers (Celery)
# CRITICAL: This is where your scan uploads are processed.
celery:
  replicas: 1
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi" # Scans can be large! Give it RAM.
      cpu: "1000m"

#PostgreSQL: The database where all vulnerabilities are stored.
# 4. The Database (PostgreSQL)
# We use the Bitnami sub-chart.
postgresql:

  auth:
    username: defectdojo
    database: defectdojo
    # Point to the shared master secret
    existingSecret: "defectdojo" 
    secretKeys:
      # Tell Postgres exactly which keys in the JSON to use
      adminPasswordKey: "POSTGRES_POSTGRES_PASSWORD" 
      userPasswordKey: "POSTGRES_PASSWORD"
  primary:
    persistence:
      enabled: true
      storageClass: "gp3" # Standard AWS storage
      size: 1Gi

# 5. The Message Broker (Redis)
# REPLACE 'redis' BLOCK WITH 'valkey' BLOCK
valkey:
  enabled: true
  architecture: standalone
  auth:
    # Point to the shared master secret
    existingSecret: "defectdojo"
    # Tell Valkey exactly which key in the JSON to use
    existingSecretPasswordKey: "VALKEY_PASSWORD"
  primary:
    persistence:
      enabled: false
