mysql:
  host: "mysql"
  port: 3306
  user: "root"
  existingPasswordSecret:
    name: "mysql-secrets"
    key: "MYSQL_ROOT_PASSWORD"
    
  # user: root
  # pass: "change_me_root_password"


serviceMonitor:
  enabled: true

podLabels:
  app: mysql-exporter
