serviceMonitor:
  enabled: true

podLabels:
  app: mongodb-exporter

existingSecret:
  name: "mongo-secrets"
  key: "mongodb-uri"

# Helm chart will mount MONGODB_URI from prometheus-mongodb-exporter secret
# containing: mongodb://admin:admin@mongodb:27017?authSource=admin
mongodb:
  uri: "mongodb://mongodb:27017"
