serviceMonitor:
  enabled: true

podLabels:
  app: mongodb-exporter

auth:
  # Reference existing secret from robotshop namespace
  existingSecret: "mongo-secrets"
  existingSecretUsernameKey: "MONGO_INITDB_ROOT_USERNAME"
  existingSecretPasswordKey: "MONGO_INITDB_ROOT_PASSWORD"

mongodb:
  # Short hostname since exporter runs in same namespace (robotshop)
  # Username and password will be injected from secret
  uri: "mongodb://mongodb:27017"