mysql:
  host: "mysql"

auth:
  # Reference existing secret from robotshop namespace
  existingSecret: "mysql-secrets"
  existingSecretPasswordKey: "MYSQL_ROOT_PASSWORD"
  username: root

serviceMonitor:
  enabled: true

podLabels:
  app: mysql-exporter
