apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongo
    env: production
    version: v1.0
    tier: database
  annotations:
    maintainer: "Double Abdelrahman"
    description: "MongoDB Service for Robot Shop Microservices"
spec:
  ports:
  - port: 27017 
  clusterIP: None
  selector:
    app: mongo
    
