apiVersion: v2
name: mongodb
description: A Helm chart for Robot Shop mongodb Service 
type: application
version: 0.1.0
appVersion: "2.1.0"

dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../_common"
